"""empty message

Revision ID: 1ade6147b537
Revises: 
Create Date: 2019-11-18 23:01:30.894282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ade6147b537'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ulica', sa.VARCHAR(), nullable=True),
    sa.Column('miasto', sa.VARCHAR(), nullable=True),
    sa.Column('kod_pocztowy', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('czynnosci',
    sa.Column('nazwa', sa.VARCHAR(), nullable=False),
    sa.Column('punktacja', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nazwa')
    )
    op.create_table('firmy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.VARCHAR(), nullable=True),
    sa.Column('nip', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienciindywidualni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pracownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('stanowisko', sa.VARCHAR(), nullable=True),
    sa.Column('uzytkownik', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zgloszenia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('powod', sa.VARCHAR(), nullable=True),
    sa.Column('organ_scigania', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aktywnosci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_aktywnosci', sa.DateTime(), nullable=True),
    sa.Column('id_pracownika', sa.Integer(), nullable=True),
    sa.Column('nazwa_czynnosci', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id_pracownika'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['nazwa_czynnosci'], ['czynnosci.nazwa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('haslo', sa.VARCHAR(), nullable=True),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imie', sa.VARCHAR(), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(), nullable=True),
    sa.Column('pesel', sa.VARCHAR(), nullable=True),
    sa.Column('adres_zamieszkania', sa.Integer(), nullable=True),
    sa.Column('adres_zameldowania', sa.Integer(), nullable=True),
    sa.Column('pracownik', sa.Integer(), nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('haslo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['adres_zameldowania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['adres_zamieszkania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['pracownik'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=True),
    sa.Column('id_firmy', sa.Integer(), nullable=True),
    sa.Column('id_klienta_indywidualnego', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_firmy'], ['firmy.id'], ),
    sa.ForeignKeyConstraint(['id_klienta_indywidualnego'], ['klienciindywidualni.id'], ),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['uzytkownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wnioski',
    sa.Column('numer_wniosku', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decyzja', sa.VARCHAR(), nullable=True),
    sa.Column('klient_id', sa.Integer(), nullable=True),
    sa.Column('zgloszenie_id', sa.Integer(), nullable=True),
    sa.Column('pracownik', sa.Integer(), nullable=True),
    sa.Column('wsk_przeterminowania', sa.DateTime(), nullable=True),
    sa.Column('kwota', sa.FLOAT(precision=2), nullable=True),
    sa.Column('rodzaj_weryfikacji', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['klient_id'], ['klienci.id'], ),
    sa.ForeignKeyConstraint(['pracownik'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['zgloszenie_id'], ['zgloszenia.id'], ),
    sa.PrimaryKeyConstraint('numer_wniosku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wnioski')
    op.drop_table('klienci')
    op.drop_table('uzytkownicy')
    op.drop_table('hasla')
    op.drop_table('aktywnosci')
    op.drop_table('zgloszenia')
    op.drop_table('pracownicy')
    op.drop_table('klienciindywidualni')
    op.drop_table('firmy')
    op.drop_table('czynnosci')
    op.drop_table('adresy')
    # ### end Alembic commands ###
