"""empty message

Revision ID: 1d0926b21601
Revises: 
Create Date: 2019-11-25 18:53:29.457758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0926b21601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ulica', sa.VARCHAR(), nullable=True),
    sa.Column('miasto', sa.VARCHAR(), nullable=True),
    sa.Column('kod_pocztowy', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('czynnosci',
    sa.Column('nazwa', sa.VARCHAR(), nullable=False),
    sa.Column('punktacja', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nazwa')
    )
    op.create_table('pracownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stanowisko', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zgloszenia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('powod', sa.VARCHAR(), nullable=True),
    sa.Column('organ_scigania', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aktywnosci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_aktywnosci', sa.DateTime(), nullable=True),
    sa.Column('id_pracownika', sa.Integer(), nullable=True),
    sa.Column('nazwa_czynnosci', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id_pracownika'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['nazwa_czynnosci'], ['czynnosci.nazwa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imie', sa.VARCHAR(), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(), nullable=True),
    sa.Column('pesel', sa.VARCHAR(), nullable=True),
    sa.Column('adres_zamieszkania', sa.Integer(), nullable=True),
    sa.Column('adres_zameldowania', sa.Integer(), nullable=True),
    sa.Column('pracownik', sa.Integer(), nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('haslo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['adres_zameldowania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['adres_zamieszkania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['pracownik'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wnioski',
    sa.Column('numer_wniosku', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decyzja', sa.VARCHAR(), nullable=True),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=True),
    sa.Column('zgloszenie_id', sa.Integer(), nullable=True),
    sa.Column('pracownik_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('kwota', sa.FLOAT(precision=2), nullable=True),
    sa.Column('typ_kredytu', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['uzytkownik_id'], ['uzytkownicy.id'], ),
    sa.ForeignKeyConstraint(['zgloszenie_id'], ['zgloszenia.id'], ),
    sa.PrimaryKeyConstraint('numer_wniosku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wnioski')
    op.drop_table('uzytkownicy')
    op.drop_table('aktywnosci')
    op.drop_table('zgloszenia')
    op.drop_table('pracownicy')
    op.drop_table('czynnosci')
    op.drop_table('adresy')
    # ### end Alembic commands ###
