"""empty message

Revision ID: 2425b608606b
Revises: 
Create Date: 2019-11-10 23:42:01.757767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2425b608606b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ulica', sa.VARCHAR(), nullable=True),
    sa.Column('miasto', sa.VARCHAR(), nullable=True),
    sa.Column('kodPocztowy', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('czynnosci',
    sa.Column('nazwa', sa.VARCHAR(), nullable=False),
    sa.Column('punktacja', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nazwa')
    )
    op.create_table('firmy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.VARCHAR(), nullable=True),
    sa.Column('nip', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienciindywidualni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pracownicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('stanowisko', sa.VARCHAR(), nullable=True),
    sa.Column('uzytkownik', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wnioski',
    sa.Column('numerWniosku', sa.Integer(), nullable=False),
    sa.Column('decyzja', sa.VARCHAR(), nullable=True),
    sa.Column('klient', sa.Integer(), nullable=True),
    sa.Column('wskPrzeterminowania', sa.DateTime(), nullable=True),
    sa.Column('kwota', sa.FLOAT(precision=2), nullable=True),
    sa.Column('rodzajWeryfikacji', sa.VARCHAR(), nullable=True),
    sa.Column('zgloszenieId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('numerWniosku')
    )
    op.create_table('zgloszenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('powod', sa.VARCHAR(), nullable=True),
    sa.Column('organScigania', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aktywnosci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataAktywnosci', sa.DateTime(), nullable=True),
    sa.Column('idPracownika', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPracownika'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.VARCHAR(), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(), nullable=True),
    sa.Column('pesel', sa.VARCHAR(), nullable=True),
    sa.Column('adresZamieszkania', sa.Integer(), nullable=True),
    sa.Column('adresZameldowania', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adresZameldowania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['adresZamieszkania'], ['adresy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUzytkownika', sa.Integer(), nullable=True),
    sa.Column('idFilmy', sa.Integer(), nullable=True),
    sa.Column('idKlientaIndywidualnego', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idFilmy'], ['firmy.id'], ),
    sa.ForeignKeyConstraint(['idKlientaIndywidualnego'], ['klienciindywidualni.id'], ),
    sa.ForeignKeyConstraint(['idUzytkownika'], ['uzytkownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klienci')
    op.drop_table('uzytkownicy')
    op.drop_table('aktywnosci')
    op.drop_table('zgloszenia')
    op.drop_table('wnioski')
    op.drop_table('pracownicy')
    op.drop_table('klienciindywidualni')
    op.drop_table('firmy')
    op.drop_table('czynnosci')
    op.drop_table('adresy')
    # ### end Alembic commands ###
