"""empty message

Revision ID: 3898c3319a48
Revises: 28aa33fbcb26
Create Date: 2019-11-21 18:42:49.624957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3898c3319a48'
down_revision = '28aa33fbcb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wnioski_pracownik_id_fkey', 'wnioski', type_='foreignkey')
    op.create_foreign_key(None, 'wnioski', 'uzytkownicy', ['pracownik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wnioski', type_='foreignkey')
    op.create_foreign_key('wnioski_pracownik_id_fkey', 'wnioski', 'pracownicy', ['pracownik_id'], ['id'])
    # ### end Alembic commands ###
