"""empty message

Revision ID: 4946564d8018
Revises: 
Create Date: 2019-11-10 13:44:12.559909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4946564d8018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zgloszenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('powod', sa.VARCHAR(), nullable=True),
    sa.Column('organScigania', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zgloszenia')
    # ### end Alembic commands ###
