"""empty message

Revision ID: 8a48a5fb1e35
Revises: d866b8fd449b
Create Date: 2019-11-21 19:56:05.089535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a48a5fb1e35'
down_revision = 'd866b8fd449b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pracownicy', 'login')
    op.drop_column('pracownicy', 'uzytkownik')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pracownicy', sa.Column('uzytkownik', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pracownicy', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
