"""empty message

Revision ID: d866b8fd449b
Revises: 3898c3319a48
Create Date: 2019-11-21 18:45:46.343267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd866b8fd449b'
down_revision = '3898c3319a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wnioski_pracownik_id_fkey', 'wnioski', type_='foreignkey')
    op.create_foreign_key(None, 'wnioski', 'pracownicy', ['pracownik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wnioski', type_='foreignkey')
    op.create_foreign_key('wnioski_pracownik_id_fkey', 'wnioski', 'uzytkownicy', ['pracownik_id'], ['id'])
    # ### end Alembic commands ###
