"""empty message

Revision ID: f9252a1607a3
Revises: 
Create Date: 2019-11-17 16:00:29.131123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9252a1607a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ulica', sa.VARCHAR(), nullable=True),
    sa.Column('miasto', sa.VARCHAR(), nullable=True),
    sa.Column('kodPocztowy', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('czynnosci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('nazwa', sa.VARCHAR(), nullable=True),
    sa.Column('punktacja', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('nazwa', sa.VARCHAR(), nullable=True),
    sa.Column('nip', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienciindywidualni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pracownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('stanowisko', sa.VARCHAR(), nullable=True),
    sa.Column('uzytkownik', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zgloszenia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('powod', sa.VARCHAR(), nullable=True),
    sa.Column('organScigania', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aktywnosci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('dataAktywnosci', sa.DateTime(), nullable=True),
    sa.Column('idPracownika', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPracownika'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('haslo', sa.VARCHAR(), nullable=True),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownicy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('imie', sa.VARCHAR(), nullable=True),
    sa.Column('nazwisko', sa.VARCHAR(), nullable=True),
    sa.Column('pesel', sa.VARCHAR(), nullable=True),
    sa.Column('adresZamieszkania', sa.Integer(), nullable=True),
    sa.Column('adresZameldowania', sa.Integer(), nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('haslo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['adresZameldowania'], ['adresy.id'], ),
    sa.ForeignKeyConstraint(['adresZamieszkania'], ['adresy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klienci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('idUzytkownika', sa.Integer(), nullable=True),
    sa.Column('idFirmy', sa.Integer(), nullable=True),
    sa.Column('idKlientaIndywidualnego', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idFirmy'], ['firmy.id'], ),
    sa.ForeignKeyConstraint(['idKlientaIndywidualnego'], ['klienciindywidualni.id'], ),
    sa.ForeignKeyConstraint(['idUzytkownika'], ['uzytkownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wnioski',
    sa.Column('numerWniosku', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('decyzja', sa.VARCHAR(), nullable=True),
    sa.Column('klient', sa.Integer(), nullable=True),
    sa.Column('pracownik', sa.Integer(), nullable=True),
    sa.Column('wskPrzeterminowania', sa.DateTime(), nullable=True),
    sa.Column('kwota', sa.FLOAT(precision=2), nullable=True),
    sa.Column('rodzajWeryfikacji', sa.VARCHAR(), nullable=True),
    sa.Column('zgloszenieId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klient'], ['klienci.id'], ),
    sa.ForeignKeyConstraint(['pracownik'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('numerWniosku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wnioski')
    op.drop_table('klienci')
    op.drop_table('uzytkownicy')
    op.drop_table('hasla')
    op.drop_table('aktywnosci')
    op.drop_table('zgloszenia')
    op.drop_table('pracownicy')
    op.drop_table('klienciindywidualni')
    op.drop_table('firmy')
    op.drop_table('czynnosci')
    op.drop_table('adresy')
    # ### end Alembic commands ###
